name: Codevanced
description: A coding diary
meta_description: "Codevanced, blogging about code"

highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://andreister.github.io'
url:            'blog url'	# Details for the RSS feed generator

author:         'Andrew Kazyrevich'
authorbio:	'Andrew is an architect, developer and data analyst, currently working on finance projects using a mixture of C# and R'
