name: Codevanced
description: Coding diary
meta_description: "Codevanced, blogging about code"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
url:            'blog url'	# Details for the RSS feed generator

author:         'Andrew Kazyrevich'
authorbio:	'Put some bio here!'
